KATRIN-Experiment/Kassiopeia

- Kassiopeia/Documentation/Reference/examples.rst
The OpenCL cmake flag has incorrect capitalization in the documentation at http://katrin-experiment.github.io/Kassiopeia/examples.html. This patch corrects the reference.
Definition is at KEMField/Source/Plugins/OpenCL/CMakeLists.txt, link https://github.com/KATRIN-Experiment/Kassiopeia/blob/3040dfd76341f2158f0433d6f450ee5e6f834b2f/KEMField/Source/Plugins/OpenCL/CMakeLists.txt#L20
> Correct cmake flag is KEMField_USE_OPENCL

- Kassiopeia/XML/CMakeLists.txt
Without the else, the final install takes precedence and overwrites
the Examples with the non-VTK version even if Kassiopeia_USE_VTK is
set, in some cases (not sure when exactly, but consistent behavior).
> Use if/else/endif on Kassiopeia_USE_VTK selector for Examples install

- Kassiopeia/Visualization/Source/KSVTKTrackTerminatorPainter.cxx
Adding `path="[output_path]"` to the <vtk_track_terminator_painter>
tag would seem to suggest that `terminator_painter.vtp` should be
written to `[output_path]`, much like is done by `track_painter.vtp`.
This commit adds the same behavior for `track_painter.vtp` to the code
handling `terminator_painter.vtp` output path.
> Respect the path attribute in the vtk_track_terminator_painter tag

- Kassiopeia/XML/Examples/AnalyticSimulation.xml
- Kassiopeia/XML/Examples/DipoleTrapMeshedSpaceSimulation.xml
- Kassiopeia/XML/Examples/DipoleTrapSimulation.xml
- Kassiopeia/XML/Examples/PhotoMultiplierTubeSimulation.xml
- Kassiopeia/XML/Examples/ToricTrapSimulation.xml
- Kassiopeia/XML/Examples/VTK/AnalyticSimulation.xml
- Kassiopeia/XML/Examples/VTK/DipoleTrapMeshedSpaceSimulation.xml
- Kassiopeia/XML/Examples/VTK/DipoleTrapSimulation.xml
- Kassiopeia/XML/Examples/VTK/PhotoMultiplierTubeSimulation.xml
- Kassiopeia/XML/Examples/VTK/QuadrupoleTrapSimulation.xml
- Kassiopeia/XML/Examples/VTK/ToricTrapSimulation.xml
Without explicit output path, the default output path is chosen, which results
in permission errors on centrally installed instances where users do not have
access to e.g. /usr/local/Kassiopeia/.
Minor other changes: tabs to 4 spaces for file alignment in xml examples.
> Add output path to kswrite_root and kswrite_vtk for DipoleTrapSimulation.xml

- CMakeLists.txt
- create_kasper_user_directory.sh.in
- kasper-krypton.bash.in
- kasperenv.sh.in
This addresses (I hope) all issues in #10 https://github.com/KATRIN-Experiment/Kassiopeia/issues/10.
New file kasper-krypton.bash with bash-completion code which is
installed to ${BIN_INSTALL_DIR} and loaded if bash is used.
> Avoid bashisms in shell scripts with /bin/sh

- KEMField/Source/Plugins/OpenCL/BoundaryIntegrals/Core/include/KOpenCLBoundaryIntegralMatrix.hh
- KEMField/Source/Plugins/OpenCL/BoundaryIntegrals/Core/include/KOpenCLBoundaryIntegralSolutionVector.hh
- KEMField/Source/Plugins/OpenCL/BoundaryIntegrals/Core/include/KOpenCLBoundaryIntegralVector.hh
- KEMField/Source/Plugins/OpenCL/BoundaryIntegrals/Electrostatic/src/KOpenCLElectrostaticBoundaryIntegrator.cc
- KEMField/Source/Plugins/OpenCL/BoundaryIntegrals/ElectrostaticNumeric/src/KOpenCLElectrostaticNumericBoundaryIntegrator.cc
- KEMField/Source/Plugins/OpenCL/BoundaryIntegrals/RWG/src/KOpenCLElectrostaticRWGBoundaryIntegrator.cc
- KEMField/Source/Plugins/OpenCL/Core/include/KOpenCLInterface.hh
- KEMField/Source/Plugins/OpenCL/Core/src/GenerateOpenCLHeader.cc
- KEMField/Source/Plugins/OpenCL/Core/src/KOpenCLKernelBuilder.cc
- KEMField/Source/Plugins/OpenCL/FastMultipole/Tree/include/KFMSparseReducedScalarMomentRemoteToLocalConverter_OpenCL.hh
- KEMField/Source/Plugins/OpenCL/FieldSolvers/Integrating/include/KOpenCLElectrostaticIntegratingFieldSolver.hh
- KEMField/Source/Plugins/OpenCL/LinearAlgebra/include/KGaussSeidel_OpenCL.hh
- KEMField/Source/Plugins/OpenCL/LinearAlgebra/include/KRobinHood_MPI_OpenCL.hh
- KEMField/Source/Plugins/OpenCL/LinearAlgebra/include/KRobinHood_OpenCL.hh
With gcc-8 catch by value is a warning enabled by -Wall, and turned into
an error by -Werror in CMakeLists.txt. This turns the catch by value
statements (in the OpenCL interface) into catch by reference.
Note: This does not solve all compiler issues in gcc-9 when compiling with USE_OpenCL=ON.
> Avoid catch by value

- Kassiopeia/Documentation/Reference/compiling.rst
The documentation indicates Kasper_USE_BOOST et al. where the CMakeFiles require KASPER_USE_BOOST with KASPER in all caps.
> KASPER cmake flags are all caps [MINOR]

- Kassiopeia/Bindings/CMakeLists.txt
- Kassiopeia/Bindings/Generators/Include/KSGenEnergyBetaRecoilBuilder.h
- Kassiopeia/Bindings/Generators/Source/KSGenEnergyBetaRecoilBuilder.cxx
- Kassiopeia/Bindings/Generators/Source/KSGenGeneratorCompositeBuilder.cxx
- Kassiopeia/Generators/CMakeLists.txt
- Kassiopeia/Generators/Include/KSGenEnergyBetaRecoil.h
- Kassiopeia/Generators/Source/KSGenEnergyBetaRecoil.cxx
Request for comments.
Below the commit message of this feature request. This implements the energy distribution of the recoiling proton of the neutron beta decay. It is based on the beta_decay generator which generates the electron energy distribution.
I have tried to stay true to the coding coding style in the beta decay generator. I am happy to make changes to this if you feel that expanded functionality would be beneficial.
I also understand if you cannot merge this into the software for distribution.
~~~
This generator, used with the tag `energy_beta_recoil` as in
```
<ksgen_generator_composite name="generator_uniform" pid="2212">
<energy_beta_recoil/>
</ksgen_generator_composite>
```
will generate an initial kinetic energy per the energy distribution
of the recoiling proton in beta …
> Feature: Neutron beta decay recoil energy generator

- CMakeLists.txt
- KEMField/Source/Plugins/OpenCL/BoundaryIntegrals/Core/include/KOpenCLBoundaryIntegrator.hh
- KEMField/Source/Plugins/OpenCL/FastMultipole/Electrostatics/include/KFMElectrostaticBatchedLocalToLocalConverter_OpenCL.hh
- KEMField/Source/Plugins/OpenCL/FastMultipole/Electrostatics/include/KFMElectrostaticBatchedRemoteToLocalConverter_OpenCL.hh
- KEMField/Source/Plugins/OpenCL/FastMultipole/Electrostatics/include/KFMElectrostaticBatchedRemoteToRemoteConverter_OpenCL.hh
- KEMField/Source/Plugins/OpenCL/FastMultipole/Electrostatics/include/KFMElectrostaticLocalToLocalConverter_OpenCL.hh
- KEMField/Source/Plugins/OpenCL/FastMultipole/Electrostatics/include/KFMElectrostaticRemoteToLocalConverter_OpenCL.hh
- KEMField/Source/Plugins/OpenCL/FastMultipole/Electrostatics/include/KFMElectrostaticRemoteToRemoteConverter_OpenCL.hh
- KEMField/Source/Plugins/OpenCL/FastMultipole/Electrostatics/src/KFMElectrostaticBatchedRemoteToRemoteConverter_OpenCL.cc
- KEMField/Source/Plugins/OpenCL/FastMultipole/Electrostatics/src/KFMElectrostaticMultipoleBatchCalculator_OpenCL.cc
- KEMField/Source/Plugins/OpenCL/FastMultipole/Electrostatics/src/KFMElectrostaticRemoteToRemoteConverter_OpenCL.cc
- KEMField/Source/Plugins/OpenCL/Surfaces/include/KOpenCLSurfaceContainer.hh
Two symptomatic fixes:
- Suppress -Wignored-attributes on all occurrences of std::vector<CL_TYPE>
- Use -faligned-new flag to trick gcc into using aligned allocators for CL types
Note: This is not stress tested, but it compiles, runs, and produces reasonable output for my use case. No guarantees on anything other than the system I am using.
The underlying concern here is that the CL_TYPEs have attributes to indicate alignment on specific byte boundaries (e.g. `typedef double cl_double  __attribute__((aligned(8)));`) which are ignored by std::vector. I am not enough of an expert to determine what the proper resolution is.
> Bugfix workarounds for gcc 9 when OpenCL enabled.

- Kassiopeia/Bindings/Generators/Source/KSGenLCompositeBuilder.cxx
- Kassiopeia/Bindings/Generators/Source/KSGenMomentumRectangularCompositeBuilder.cxx
- Kassiopeia/Bindings/Generators/Source/KSGenNCompositeBuilder.cxx
- Kassiopeia/Bindings/Generators/Source/KSGenPositionFluxTubeBuilder.cxx
- Kassiopeia/Bindings/Generators/Source/KSGenTimeCompositeBuilder.cxx
Some bindings have ifdef guards with KASSIOPEIA_USE_ROOT, however in
Kassiopeia/CMakeLists.txt the line `SET( Kassiopeia_USE_ROOT
${KASPER_USE_ROOT} )` sets Kassiopeia_USE_ROOT. This causes the bindings
for, for example, momentum_rectangular_composite not to accept histogram
input on case sensitive compilers.
This bugfix replaces all instances of KASSIOPEIA_USE_ROOT with
Kassiopeia_USE_ROOT.
> Use Kassiopeia_USE_ROOT instead of KASSIOPEIA_USE_ROOT

- KEMField/Source/Plugins/OpenCL/Core/include/KOpenCLInterface.hh
On gcc-9, with `-DKEMField_USE_OPENCL=ON` and `-Werror` in CMakeLists.txt, the narrowing from doubles to CL_TYPE in initializer lists results in an error, e.g. https://github.com/KATRIN-Experiment/Kassiopeia/blob/4065e02e04f627c37ae306e77268edf275c4d7c8/KEMField/Source/Plugins/OpenCL/BoundaryIntegrals/Electrostatic/include/KOpenCLElectrostaticBoundaryIntegrator.hh#L136, 
```
template <class SourceShape>
double KOpenCLElectrostaticBoundaryIntegrator::Potential(const SourceShape* source,const KPosition& aPosition) const
{
StreamSourceToBuffer(source);
CL_TYPE P[3] = {aPosition[0],aPosition[1],aPosition[2]};
```
with KPosition using double.
This fix just pushes GCC to ignore "-Wnarrowing". This may not fix compilation on other compilers, but then again, maybe the warning doesn't result in an …
> Bugfix: If CL_TYPE is set to float, we don't want narrowing warnings

- KEMField/Source/IO/StructuredASCII/CMakeLists.txt
- KEMField/Source/IO/StructuredASCII/include/miniz.c
- KEMField/Source/IO/StructuredASCII/include/miniz.hh
- KEMField/Source/IO/StructuredASCII/src/KSAFileWriter.cc
With `-DKEMField_USE_ZLIB=OFF` there are a number of compiler errors (mainly `enumeral and non-enumeral type in conditional expression`). Rather than fix the issues in miniz, I just upgraded miniz to a newer released upstream version (version 1.15 in 3.6.1 was from 2013, current release version is 2.1.0 from 2019). This indeed fixed most compiler errors, with the exception of one, https://github.com/richgel999/miniz/pull/154 submitted upstream and included here.
> Bugfix: miniz upgrade

- KEMField/Source/Plugins/OpenCL/CMakeLists.txt
The variables OPENCL_LIBRARIES and OPENCL_INCLUDE_DIRS lead to problems on (at least) Ubuntu 19.10, CMake 3.13.4.
> Bugfix: `find_package(OpenCL REQUIRED)` delivers variables OpenCL_*

- KEMField/Source/Plugins/OpenCL/Core/include/KOpenCLHeaderWrapper.hh
- KEMField/Source/Plugins/OpenCL/Core/src/GenerateOpenCLHeader.cc
This defines the target to OpenCL 1.2 on all non-__APPLE__ systems (which I have no way to test). Without an explicit version, there are warnings every time cl.hpp is included.
> OpenCL warns unless CL_TARGET_OPENCL_VERSION is set to target version

- kasperenv.sh.in
Or, it was merged in PR #13 but not propagated to the new master.
> Bugfix: kasper-krypton.bash was removed, so no need to load it anymore.

- Kassiopeia/Generators/Source/KSGenGeneratorSimulation.cxx
- Kassiopeia/Readers/Include/KSReadIteratorROOT.h
- Kassiopeia/Readers/Include/KSReadObjectROOT.h
- Kassiopeia/Readers/Include/KSReadSet.h
- Kassiopeia/Readers/Include/KSReadValue.h
- Kassiopeia/Readers/Source/KSReadIterator.cxx
- Kassiopeia/Readers/Source/KSReadObjectROOT.cxx
This introduces KSLongLong in reading ROOT files in the KSGenGeneratorSimulation. In particular, the PID values are written as long long.
> Bugfix: KSRead for long long type

- KGeoBag/Source/Extensions/Mesh/Complex/Source/KGConicSectPortHousingSurfaceMesher.cc
- KGeoBag/Source/Extensions/Mesh/Complex/Source/KGPortHousingSurfaceMesher.cc
The lines with `dz.empty()` generate a compilation error on gcc-10 due to `-Werror` and `-Wunused-result` in particular. Instead of `dz.empty()` I suspect it should be `dz.clear()`.
References:
- [bool empty()](http://www.cplusplus.com/reference/vector/vector/empty/)
- [void clear()](http://www.cplusplus.com/reference/vector/vector/clear/)
Compilation error:
```
[ 25%] Built target KGeoBagRandom
/home/wdconinc/git/Kassiopeia/KGeoBag/Source/Extensions/Mesh/Complex/Source/KGConicSectPortHousingSurfaceMesher.cc: In member function ‘void KGeoBag::KGConicSectPortHousingSurfaceMesher::ParaxialPortDiscretizer::DiscretizePort(const KGeoBag::KGConicSectPortHousing::ParaxialPort*)’:
/home/wdconinc/git/Kassiopeia/KGeoBag/Source/Extensions/Mesh/Complex/Source/KGConicSectPortHousingSurfaceMesher.cc:820 …
```
> [bugfix] std::vector empty() just checks for emtpiness; clear() acts on the vector

- KEMField/Source/Plugins/VTKPart2/src/KElectrostaticPotentialmap.cc
- KEMField/Source/Plugins/VTKPart2/src/KMagnetostaticFieldmap.cc
When only a magnetic field grid is available, no gradient of the field, Kassiopeia crashes hard due to a null pointer `data`, see e.g. below. This bugfix adds a `return false` when `data` is a nullptr. In that case, a proper warning inside Kassiopeia is given:
```
[KEMFIELD NORMAL MESSAGE] WARNING: could not compute magnetic gradient at sample point 
<KPosition>
<0>(double)-1.85045e-05<\0>
<1>(double)0.0971891<\1>
<2>(double)1.1351<\2>
<\KPosition>
```
Original crash backtrace:
```
[KSMAIN NORMAL MESSAGE] ☻   welcome to Kassiopeia 3.7.4  ☻ 
****[KSRUN NORMAL MESSAGE] processing run 0 ...
********[KSEVENT NORMAL MESSAGE] processing event 0 <generator_proton_along_positive_z_decay> ...
************[KSTRACK NORMAL MESSAGE] processing track 0 <generator_proton_along_positive_z_decay> ... …
```
> [bugfix] avoid hard crash when gradient not present in maps

- CMakeLists.txt
When Kassiopeia is linked against ROOT, the [same C++ standard must be used](https://root.cern/install/build_from_source/#setting-the-c-standard), i.e. linking against ROOT compiled with C++17 requires compiling Kassiopeia with `CMAKE_CXX_STANDARD=17`. This becomes more and more relevant as other frameworks start to rely on ROOT compiled with C++17. Linking Kassiopeia against C++17 is an advantage as it would otherwise require a parallel ROOT installation. Kassiopeia linked against ROOT compiled with C++17 works just fine as it is; no changes needed.
However, currently specifying `-DCMAKE_CXX_STANDARD=17` on the cmake command line does not take any effect, because of the `set(CMAKE_CXX_STANDARD=14)` line. By modifying that line to set a [cache …
> Enhancement: [cmake] default to CMAKE_CXX_STANDARD=14 but allow override

- Kassiopeia/Bindings/Visualization/Include/KSROOTTrackPainterBuilder.h
- Kassiopeia/Bindings/Visualization/Source/KSROOTTrackPainterBuilder.cxx
- Kassiopeia/Visualization/Include/KSROOTTrackPainter.h
- Kassiopeia/Visualization/Source/KSROOTTrackPainter.cxx
`root_geometry_painter` already had an option to project on an arbitrary plane, defined by point and normal. E.g.
```xml
<root_window
name="root_window_xy"
canvas_width="1024"
canvas_height="1024"
write_enabled="false"
path="[output_path]"
>
<root_geometry_painter
name="root_geometry_painter_xy"
surfaces="world/proton_trap/#"
plane_normal="0 {sin(18.*[deg])} {cos(18.*[deg])}"
plane_point="{[detector_x]} {[detector_y]} {[detector_z]}"
swap_axis="false"
/>
</root_window>
```
However, this was not possible for the `root_track_painter`, not for `plot_mode="track"` nor for `plot_mode="step"`.
This commits adds support for the same syntax to the ROOT track painter, while (of course) keeping backwards compatibility. This will now require specifying axes `a` and `b`. E.g.
```xml …
```
> Feature: ROOT track painter arbitrary plane defined by point and normal

- Kassiopeia/Visualization/Source/KSROOTMagFieldPainter.cxx
In `<root_magfield_painter>` visualizations, `tGradB` is set to B·∇B, but is not normalized by |B|. This normalizes the quantity property. Now `magnetic_gradient_numerical="false"` and `magnetic_gradient_numerical="true"` give the same result.
> Bugfix: Gradient plotting requires dividing by |B|, not multiplying

- KEMField/Source/Bindings/Fields/Magnetic/include/KStaticElectromagnetFieldBuilder.hh
- KEMField/Source/Bindings/Fields/Magnetic/src/KStaticElectromagnetFieldBuilder.cc
- KEMField/Source/Interface/Fields/Magnetic/include/KStaticElectromagnetField.hh
- KEMField/Source/Interface/Fields/Magnetic/src/KStaticElectromagnetField.cc
- KEMField/Source/Interface/KGeoBag/include/KGElectromagnetConverter.hh
- KEMField/Source/Interface/KGeoBag/include/KGStaticElectromagnetField.hh
- KEMField/Source/Interface/KGeoBag/src/KGElectromagnetConverter.cc
- KEMField/Source/Interface/KGeoBag/src/KGStaticElectromagnetField.cc
In configurations such as
```xml
<electromagnet_field
name="magnetic_field_electromagnet"
directory="[KEMFIELD_CACHE]"
save_magfield3="true"
file="ProtonTrapMagnets.kbd"
system="world/proton_trap"
spaces="world/proton_trap/@magnet_tag"
>
```
the mag3 files are not saved in the directory immediately above. This is counter-intuitive, but even worse when using docker or singularity containers it defaults to a non-writable location. This also affects some examples, such as DipoleTrapSimulation.xml.
This pull request introduces a public getter for the directory (and file) of the underlying `KStaticElectromagnetField` which is then used by `KGStaticElectromagnetField` to instruct `KGElectromagnetConverter` to write to the directory location.
This pull request also ensures that failure to open …
> Bugfix: new save_magfield3 should respect directory in same element

- KEMField/Source/Bindings/Fields/Magnetic/include/KMagneticSuperpositionFieldBuilder.hh
- KEMField/Source/Bindings/Fields/Magnetic/include/KMagnetostaticFieldmapBuilder.hh
- KEMField/Source/Bindings/Fields/Magnetic/src/KMagneticSuperpositionFieldBuilder.cc
- KEMField/Source/Bindings/Fields/Magnetic/src/KMagnetostaticFieldmapBuilder.cc
- KEMField/Source/Interface/Fields/Magnetic/include/KMagneticField.hh
- KEMField/Source/Interface/Fields/Magnetic/include/KMagneticSuperpositionField.hh
- KEMField/Source/Interface/Fields/Magnetic/include/KMagnetostaticField.hh
- KEMField/Source/Interface/Fields/Magnetic/src/KMagneticSuperpositionField.cc
- KEMField/Source/Plugins/VTKPart2/include/KMagnetostaticFieldmap.hh
- KEMField/Source/Plugins/VTKPart2/src/KMagnetostaticFieldmap.cc
This implements a solution to #39 to allow magnetic field superpositions that occupy different regions in space. A use case is to stitch together _N_ magnetic field maps without complaining about missing field values in _N-1_ of the maps for every point.
This introduces `magnetic_field_superposition` syntax such as:
```xml
<magnetic_superposition_field
name="magnetic_field_electromagnet"
use_caching="true"
require="one"
>
```
where `require` can take values `all` (default, previous behavior), `any` (i.e. at least one), `one` (i.e. exactly one), or `none` (i.e. don't care even if no values are present). Technically, `none` could be any other value.
This also introduces `magnetic_fieldmap` syntax such as:
```xml
<magnetic_fieldmap
name="magnetic_field_electromagnet_0-80" …
```
> Feature: fieldmap superposition with position check and requirement options

- Kassiopeia/Applications/Validation/CMakeLists.txt
Without this bugfix, builds on systems without VTK fail.
Ref: https://github.com/KATRIN-Experiment/Kassiopeia/blob/v3.8.0/Kassiopeia/Applications/Validation/Source/TestField.cxx#L4
> TestField.cxx needs VTK: build if KEMField_USE_VTK

- CMakeLists.txt
- KGeoBag/Source/Visualization/Vtk/Source/KGVTKGeometryPainter.cc
Two minor fixes to get Kassiopeia to compile against VTK 9 (9.0.3 in my case).
- vtkUnsignedCharArray is not automatically included through vtkPolyData anymore
- MPI C compiler (used in vtk) needs LANGUAGES C in Kassiopeia (https://gitlab.kitware.com/vtk/vtk/-/issues/17734)
> Minor fixes for VTK 9

- KEMField/Source/Bindings/Fields/Magnetic/include/KMagnetostaticFieldmapBuilder.hh
- KEMField/Source/Bindings/Fields/Magnetic/src/KMagnetostaticFieldmapBuilder.cc
- KEMField/Source/Plugins/VTKPart2/include/KMagnetostaticFieldmap.hh
- KEMField/Source/Plugins/VTKPart2/src/KMagnetostaticFieldmap.cc
In response to issue #57 .
I added a time parameter to KMagnetostaticFieldmapCalculator(Builder) and changed the type from fMagneticField to KMagnetostaticField to KMagneticField. This allows to calculate fieldmaps also for non-static fields by giving an evaluation time. The default evaluation time is 0. 
The KMagnetostaticFieldmap is not changed as the stored field does not have time dependence stored and thus is still a KMagnetostaticField.
The code compiles without any problems. The code was tested by calculating and exporting a fieldmap from a KMagneticSuperpositionField (which is a KMagneticField but not a KMagnetostaticField). Inspection of the created VTI file shows the expected behaviour.
> Add time functionality to KMagnetostaticFieldmapCalculator(Builder)

- KEMField/Source/Plugins/Root/src/KEMRootFieldCanvas.cc
This avoids the 'use after fclose' error where `fclose(inputwire)` is already unconditionally handled before the `fclose(inputwire)` removed in this PR.
> Avoid use inputwire after fclose

- Docker/packages.build
- Docker/packages.runtime
- Dockerfile
- Scripts/update-docker.sh
Update the docker version to Fedora38. this fixes some build issues arising from an outdated root installation in Fedora31.
> Update docker version to Fedora38 to fix build issues

- Kommon/Base/CMakeLists.txt
- Kommon/Base/Utility/KConst.h.in
- Kommon/Base/Utility/KConst_2021.h
When using Kassiopeia as an external library, as described in #72 there were compilation issues observed, likely because of missing definition of the rerefence epoch. This commit fixes that by ensuring the corresponding compile-time constant to be baked into the corresponding header file.
Btw. an alternative approach would maybe include adding this variable to the `KommonConfig.cmake` file via `add_compile_definitions` (or `target_compile_definitions`), which however is less portable since that requires others to use the CMake build system to get the correct variables. The downside of this solution is that it only fixes the issue for KConst, the same type of issues may also appear for other flags that are added via `target_compile_definitions`. Since we didn't have any issues with that so …
> Kommon: Bake KConst epoch into header file

- Dockerfile
Since the update to Fedora 38 in #77 , terminals were no longer accessible in MyBinder. This is due to the JupyterLab configuration in `/etc/jupyter` being overwritten by a bind mount of MyBinder - for Fedora 36, `/etc/jupyter` was not used for terminal configuration and therefore this problem only occurs now..
> Docker: Fix terminals in MyBinder

- Documentation/gh-pages/source/compiling.rst
This Updates the dependencies and version numbers to the values in the newest found in the README (and some from the Kasper installation manual) and adds substitutions for each mention to streamline version numbers
> Documentation: Dependencies and version numbers updated

- Kassiopeia/Objects/Include/KSComponentMath.h
https://root.cern.ch/doc/master/classTROOT.html manages and deletes all ROOT objects, among which are also `TF1` objects created by `KSComponentMath`. So far, they were also deleted by `KSComponentMath`, causing in a segmentation fault.
There are two options:
* Removing the object from `TROOT`
* Not deleting the object in `KSComponentMath`
This commit goes for the latter. Note that while the general mechanics was already tested, this concrete code change was done in the GitHub Web IDE and therefore may contain typos, so one should just merge it after the CI finishes the tests.
Btw. it would be awesome to have Unit tests for `KSComponent`s (i.e. for everything that is a Kassiopeia `output`), but it seems to be a bit complex to set them up. Maybe that's an interesting challenge for later.
> KSComponentMath: Fix segfault during destruction

- Documentation/gh-pages/source/kemfield_manual.rst
- KEMField/Source/Plugins/OpenCL/CMakeLists.txt
This fixes using Kassiopeia as a CMake submodule with OpenCL
enabled. Previously, a path relative to the project binary base
path was used to store a temporary binary. Now a path relative
to the binary base path of the current submodule is used.
> Build: Fix Kassiopeia as submodule 

- Kassiopeia/Utility/Include/KSList.h
Some controls/interactions showed warnings about being added twice even if just the same parent type was
added twice.
This is an alternative approach to #76 , just showing the messages if relevant instead of changing their log level and content.
> Fix warnings about adding controls/interactions multiple times

- Kassiopeia/Simulation/Include/KSRoot.h
- Kassiopeia/Simulation/Source/KSRoot.cxx
A minor improvement: The toolbox doesn't need to be a member of `KSRoot`.
> Kassiopeia: Remove KSRoot::fToolbox

- .github/workflows/github-pages.yml
Due to PEP 668, the recommended way to nowadays install Python software via `pip` is by creating a virtual environment. There are alternatives, but they are not recommended. Since this is required for our CI to work, this pull request adds a simple virtual environment.
> CI: Fix GitHub pages

- KGeoBag/Source/Core/Source/KGInterface.cc
This warning informs users about a possible configuration mistake --> See #118.
> Add warning when user sets a tag instead of a distinct geometry path
